const now = new Date();
const currentYear = now.getFullYear();
const currentMonth = now.getMonth();

export default [
	{
		id: 0,
		title: "All Day Event very long title",
		allDay: true,
		start: new Date(currentYear, currentMonth, 1),
		end: new Date(currentYear, currentMonth, 2),
		task: "Task 0",
		project: "Project 0",
	},
	{
		id: 1,
		title: "Long Event",
		start: new Date(currentYear, currentMonth, 7),
		end: new Date(currentYear, currentMonth, 10),
		task: "Task 1",
		project: "Project 1",
	},
	{
		id: 2,
		title: "DTS STARTS",
		start: new Date(currentYear, currentMonth, 13),
		end: new Date(currentYear, currentMonth, 20),
		task: "Task 2",
		project: "Project 2",
	},
	{
		id: 3,
		title: "DTS ENDS",
		start: new Date(currentYear, currentMonth, 6),
		end: new Date(currentYear, currentMonth, 13),
		task: "Task 3",
		project: "Project 3",
	},
	{
		id: 4,
		title: "Some Event",
		start: new Date(currentYear, currentMonth, 9),
		end: new Date(currentYear, currentMonth, 10),
		task: "Task 4",
		project: "Project 4",
	},
	{
		id: 5,
		title: "Conference",
		start: new Date(currentYear, currentMonth, 11),
		end: new Date(currentYear, currentMonth, 13),
		desc: "Big conference for important people",
		task: "Task 5",
		project: "Project 5",
	},
	{
		id: 6,
		title: "Meeting",
		start: new Date(currentYear, currentMonth, 12, 10, 30, 0, 0),
		end: new Date(currentYear, currentMonth, 12, 12, 30, 0, 0),
		desc: "Pre-meeting meeting, to prepare for the meeting",
		task: "Task 6",
		project: "Project 6",
	},
	{
		id: 7,
		title: "Lunch",
		start: new Date(currentYear, currentMonth, 12, 12, 0, 0, 0),
		end: new Date(currentYear, currentMonth, 12, 13, 0, 0, 0),
		desc: "Power lunch",
		task: "Task 7",
		project: "Project 7",
	},
	{
		id: 8,
		title: "Meeting",
		start: new Date(currentYear, currentMonth, 12, 14, 0, 0, 0),
		end: new Date(currentYear, currentMonth, 12, 15, 0, 0, 0),
		task: "Task 8",
		project: "Project 8",
	},
	{
		id: 9,
		title: "Happy Hour",
		start: new Date(currentYear, currentMonth, 12, 17, 0, 0, 0),
		end: new Date(currentYear, currentMonth, 12, 17, 30, 0, 0),
		desc: "Most important meal of the day",
		task: "Task 9",
		project: "Project 9",
	},
	{
		id: 10,
		title: "Dinner",
		start: new Date(currentYear, currentMonth, 12, 20, 0, 0, 0),
		end: new Date(currentYear, currentMonth, 12, 21, 0, 0, 0),
		task: "Task 10",
		project: "Project 10",
	},
	{
		id: 11,
		title: "Planning Meeting with Paige",
		start: new Date(currentYear, currentMonth, 13, 8, 0, 0),
		end: new Date(currentYear, currentMonth, 13, 10, 30, 0),
		task: "Task 11",
		project: "Project 11",
	},
];
